import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Navbar from './_components/navbar/navbar';
import './globals.css';
import { Toaster } from 'sonner';
import NextAuthProvider from './providers/provider.Auth';
import Providers from './providers/providers';
import Footer from './_components/footer/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextAuthProvider>
            <Toaster />
            <Navbar />
            {children}
          </NextAuthProvider>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
